Repository bilalix/arabic-reshaper-app, pull requests merged in 2021-08, with the labels that each got.

#2 Deploy to GitHub
  package-lock.json
  package.json
  src/ArabicForm.js
  src/theme.js
Labels: deployment

#1 Add Dark Theme
  README.md
  src/App.js
  src/AraAppBar.js
  src/theme.js
Labels: enhancement

#3 Fix tajawal font
  README.md
  src/App.js
  src/Header.js
  src/index.css
  src/index.js
Labels: good first issue

#9 Heavy refactoring and adding Router
  .github/workflows/main.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  public/images/homepage.png
  public/images/logo.png
  public/logo_src.zip
  public/screenshot.png
  src/App.js
  src/App.test.js
  src/AraAppBar.js
  src/AraRoutes.js
  src/Home.js
  src/Layout.js
  src/components/AraFooter.js
  src/components/AraForm.js
  src/components/AraHeader.js
  src/components/AraNotFound.js
  src/components/AraTopBar.js
  src/docs/HowItWorks.js
  src/themes/CustomThemeProvider.js
  src/themes/base.js
  src/themes/dark.js
  src/themes/normal.js
Labels: Refactoring

#11 Add how it works page
  README.md
  src/docs/HowItWorks.js
Labels: documentation
